ppwnadia/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
import profilenadia.urls as profilenadia
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(profilenadia)),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

profilenadia/urls.py
from django.urls import path

from .views import *

app_name ='profilenadia'
urlpatterns = [
    path('', index, name='index'),
    path('portofolio/', portofolio, name = 'portofolio'),
    path('register/', register, name ='register'),
    path('schedule', schedule, name='schedule'),
    path('schedule_pos/', schedule_pos, name ='schedule_pos'),
    path('schedule_get', schedule_get, name='schedule_get'),
    path('delete_all', delete_all, name = 'delete_all'),
]

profilenadia/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Schedule(models.Model):
    nama_kegiatan = models.CharField(max_length = 30)
    tempat = models.CharField(max_length = 30)
    kategori = models.CharField(max_length = 30)
    date = models.DateTimeField()

story6/models.py
from django.db import models

# Create your models here.

profilenadia/forms.py
from django import forms
from .models import Schedule

class Agenda_Form(forms.Form):
    attrs = {
        'class' : 'form-control'
        }
    nama_kegiatan = forms.CharField(label= 'Nama Kegiatan', required = True, max_length= 27,
                           empty_value= 'Anonymous',widget= forms.TextInput(attrs=attrs))
    date = forms.DateField(label = 'Date', widget = forms.DateInput(attrs = {'type':'date'}))
    tempat = forms.CharField(label = 'Tempat', required = True, max_length= 27,
                            widget = forms.TextInput(attrs=attrs))
    kategori = forms.CharField(label= 'Kategori', required = True, max_length= 27,
                           empty_value= 'Anonymous',widget= forms.TextInput(attrs=attrs))
    time = forms.TimeField(
        label = 'Time',
        widget = forms.TimeInput(attrs = {'type':'time'})
    )

profilenadia/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from .forms import Agenda_Form
from .models import *
from . import forms


def index(request):
    response = {}
    return render(request, 'index.html', response)

def portofolio(request):
    response = {}
    return render(request, 'page2.html', response)

def register(request):
    response = {}
    return render(request, 'register.html', response)

def schedule_pos(request):
    form = Agenda_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response = {}
        response['nama_kegiatan'] = request.POST['nama_kegiatan']
        response['tempat'] = request.POST['tempat']
        response['kategori'] = request.POST['kategori']
        response['date'] = request.POST['date']
        schedule = Schedule(nama_kegiatan=response['nama_kegiatan'], tempat=response['tempat'], kategori=response['kategori'], date= response['date'])
        schedule.save()
        response = {}
        schedule = Schedule.objects.all()
        response['schedule'] = schedule
        html ='schedule.html'
        return render(request, html , response)
    else:
        return HttpResponseRedirect('/')

def schedule(request):
    response = {}
    response['Agenda_Form'] = Agenda_Form
    return render(request, 'create_sced.html', response)

def schedule_get(request):
    response = {}
    schedule = Schedule.objects.all()
    response['schedule'] = schedule
    html ='schedule.html'
    return render(request, html, response)


def delete_all(request):
    Schedule.objects.all().delete()
    response = {}
    html = 'schedule.html'
    return render(request, html, response)

story6/views.py
from django.shortcuts import render

# Create your views here.

profilenadia/templates/create_sced.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="grid-x" style="margin: 20px">
    <div class="cell small-1">

    </div>
    <div  style="background: #eaeaea; padding: 25px; border-radius: 30px" class="cell small-10">
        <section name="form">
            <h2 style="color: #2c3e50">Create Schedule</h2>
            <form action="{% url 'profilenadia:schedule_pos' %}" id="form", method="POST">
                {% csrf_token %}
                {{ Agenda_Form }}
                <br>
                <button type="submit" class="button">Submit</button>
            </form>
        </section>
    </div>
    <div class="cell small-1"></div>

</div>


  </body>
</html>

profilenadia/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="icon" href="https://banner2.kisspng.com/20180330/whq/kisspng-common-daisy-flower-white-stock-photography-daisy-5abee3d5168134.7019189615224596050922.jpg" type="image/gif" sizes="16x16">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="{%static "css/styles.css" %}">

		<!-- Conditional comment containing JS files for IE6 - 8 -->
		<!--[if lt IE 9]>
			<script src="assets/js/html5.js"></script>
			<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>


		{% block content %}{% include 'navbar.html' %}{% endblock %}

			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6">
					<div class="whitebox" id="border1">
						<img id="display" src="{%static "img/Nadia.jpg" %}"; width="150"; height="150">
						<h1 id="Headerfont1"> Nadia Syafitri </h1>
						<h4 id="itemfont2"> Jakarta, January 17th 2000<h4>
							<p id="itemfont3"> I'm currently pursuing Computer Science Degree <br>
								at University of Indonesia</p>

					</div>
				</div>
				<div class="col-sm-6">
					<div class="educationbox">
						<div class="row" id="row-1">
							<p id= timeline1>SMPN 85 Jakarta <br> &nbsp &nbsp &nbsp 2011-2014</p>
						</div>
						<div class="row">
							<p id= timeline2>SMAN 34 Jakarta <br> &nbsp &nbsp &nbsp 2014-2017</p>
						</div>
					</div>
					<h1 id="Headerfont2"> EDUCATION </h1>
				<br>
				</div>
			</div>
			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6" >
					<div class="row-md-2" style="padding-bottom:20px;">
					<div class="bluebox">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/5dbf16c6dbb044f4b346c47d81a5a89f?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/b8427b2b677f445398dd0fe7997a9eb6?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/beaa9dc0e4c24fb69ea74082ee0ebd31?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/7f301779ee8f4fb6a658ac5330c3bfd6?quality=95&fake=.png"; width="80"; height="80">
					</div>
						<div class="educationbox" id="orangesize">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/d684d74b26054e07ab4fbe63c4407f06?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/0053c5ff84624f6e821744e5b147e4e9?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/780c1e37d53c4da6a49e9bb0e7ae99e4?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/9ca0b19918a84353829b8cebdef85c57?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/4325f6b78681421597583a5b7ce8fc1c?quality=95&fake=.png"; width="80"; height="80">
						</div>
					</div>
				</div>

				<div class="col-sm-6">
					<div class="element">
					<h3 class="UIUXmargin" id="Headerfont"> UI/UX Designer </h3>
					<div class="caption UIUXmargin">
						<ol id="itemfont">
							<li> Gathering and evaluating user requirements, in collaboration with product managers and engineers </li>
							<li> Illustrating design ideas using storyboards, process flows and sitemaps </li>
							<li>Designing graphic user interface elements, like menus, tabs and widgets</li>
						</ol>
					</div>
				</div class="row">
				<h1 id="Headerfont2"> WORK EXPERIENCE </h1>
				</div>
			</div>
			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6">
					<div class="educationbox">
						<h3 class="UIUXmargin" id="Headerfont">COMPFEST X</h3>
							<h5 class="UIUXmargin" id="italic"> Staff of Playground</h5>
						<ul id="itemfont4">
							<li>Person in Charge Playground on Main Event</li>
							<li>Person in Charge Open Registration Playground</li>
							<li>Approached more than 20 IT startups for the exhibiton.</li>
					</div>
					<h1 id="Headerfont2"> VOLUNTEERS </h1>
				</div>
				<div class="col-sm-6">
					<div class="whitebox" id="border2">
						<img id="display2" src="https://i.pinimg.com/564x/2e/4b/c5/2e4bc5ab1f9cdbc10d54bdac33d26ccb.jpg"; width="150"; height="150">
					</div>
					<h1 id="Headerfont2"><a href="{% url 'profilenadia:portofolio'%}"> PORTOFOLIO</a> </h1>
				</div>
			</div>
			<!-- /.row -->


		<!-- JQuery scripts -->
	    <script src="{%static "js/jquery-1.11.2.min.js"%}"></script>

		<!-- Bootstrap Core scripts -->
		<script src="{%static "js/bootstrap.min.js"%}"></script>
  </body>
</html>

profilenadia/templates/navbar.html
{% block content %}
<nav class="navbar navbar-fixed-top" style="background-color: #F9FAD1" role="navigation">
<div class="container-fluid">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'profilenadia:index' %}">Nadia Syafitri</a>
  </div>
  <!-- /.navbar-header -->

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="{% url 'profilenadia:register' %}">Register</a></li>
      <li><a href ="{% url 'profilenadia:schedule_get' %}">Schedule</a></li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
{% endblock %}

profilenadia/templates/page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portofolio</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static "css/thumbnail-gallery.css"%}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    {% block content %}{% include 'navbar.html' %}{% endblock %}


    <!-- Page Content -->
    <div class="container">

      <h1 class="my-4 text-center text-lg-left">Portofolio</h1>

      <div class="row text-center text-lg-left">

        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1935071/screenshots/4575482/sdfsffd.png" alt="" >
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://i.pinimg.com/564x/b1/2e/17/b12e17bb7ea033364c121a5e8a2594a7.jpg" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1094383/screenshots/4674641/hq2.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1588664/screenshots/4539133/0000.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1588664/screenshots/4677338/end.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/2933/screenshots/4660545/ezgif.com-video-to-gif-long.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/793057/screenshots/3031884/pull-to-refresh_1.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1167581/screenshots/3135876/render.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/93245/screenshots/2947795/job_app_concept.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/572419/screenshots/4477691/set7.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/507649/screenshots/3439906/afterpay_app_onboarding.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/62549/screenshots/4578758/booksley.gif" alt="">
          </a>
        </div>
      </div>

    </div>
    <!-- /.container -->


    <!-- Bootstrap core JavaScript -->
    <script src="{%static "js/jquery.min.js"%}"></script>
    <script src="{%static "js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

profilenadia/templates/register.html
{% load static %}
<DOCTYPE! html>

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Register Account</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
  <meta name="author" content="nadia.syafitri@ui.ac.id">
  <meta name="robots" content="index, follow">

  <!-- icons -->
  <link rel="icon" href="https://banner2.kisspng.com/20180330/whq/kisspng-common-daisy-flower-white-stock-photography-daisy-5abee3d5168134.7019189615224596050922.jpg" type="image/gif" sizes="16x16">

  <!-- Bootstrap Core CSS file -->
  <link rel="stylesheet" href="{%static "css/bootstrap.min.css" %}">

  <!-- Override CSS file - add your own CSS rules -->
  <link rel="stylesheet" href="{%static "css/styles.css" %}">

  <body>
    <!-- Navigation -->
      {% block content %}{% include 'navbar.html' %}{% endblock %}
        <!-- /.navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#"></a></li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <!-- /.navbar -->

  <div class="row-md-12">
    <div class="column-md-6">
    <div class="registerbox">
      <h1 id="registerfont"> Register Yourself</h1>
      <div class="row-md-1">
        <div class="col-md-3">
      <div class="form-group">
        <label id="regfont" for="usr">Name:</label>
        <input type="text" class="form-control" id="usr">
      </div>
            <div class="form-group">
              <label id="regfont" for="usr">Birthdate:</label>
              <input type="date" class="form-control" id="usr">
            </div>
            <div class="form-group">
                <label id="regfont" for="usr"> Email:</label>
                <input type="email" class="form-control" id="usr">
              </div>
              <div class="form-group">
                <label id="regfont" for="usr">Username:</label>
                <input type="text" class="form-control" id="usr">
              </div>
              <div class="form-group">
                <label id="regfont" for="usr">Password:</label>
                <input type="password" class="form-control" id="usr">
              </div>
              <div class="form-group">
                <label id="regfont" for="usr">Password Confirmation:</label>
                <input type="password" class="form-control" id="usr">
              </div>
              <div class="regbutton">
              <input type="button" onclick="alert('Registered!')" value="register">
            </div>
              </div>
              </div>
            </div>
          </div>
        </div>









  </body>
</head>
</html>

profilenadia/templates/schedule.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="icon" href="https://banner2.kisspng.com/20180330/whq/kisspng-common-daisy-flower-white-stock-photography-daisy-5abee3d5168134.7019189615224596050922.jpg" type="image/gif" sizes="16x16">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="{%static "css/styles.css" %}">

		<!-- Conditional comment containing JS files for IE6 - 8 -->
		<!--[if lt IE 9]>
			<script src="assets/js/html5.js"></script>
			<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
    {% block content %}{% include 'navbar.html' %}{% endblock %}
    <div class="container">
    <div class="col-1">
      <div class="row-md-10">
    <section name="form">
          <h2>Write your Schedule!</h2>
          <form id="form" method="POST" action="{% url 'profilenadia:schedule' %}">
              {% csrf_token %}
              {{ Agenda_Form }}
              <br>
              <button type="submit" class="save btn btn-default">Add</button>
							<a href="{% url 'profilenadia:delete_all' %}"  class="save btn btn-default">Delete All</a>
          </form>
      </section>
    </div>
  </div>

<div class="container">
  <div class="col-md-7">
  <div class="row-md-10">
      <table class="table">
        <thead>
            <th>Name of activity</th>
            <th>Place</th>
            <th>Date</th>
            <th>Time</th>
            <th>Category</th>
        </thead>
            <tbody>
                {% for i in schedule %}
                <tr>
                    <td> {{ i.nama_kegiatan }} </td>
                    <td> {{ i.tempat }} </td>
                    <td> {{ i.date }} </td>
                    <td> {{ i.time }} </td>
										<td> {{ i.kategori }} </td>
									 </tr>
                {% endfor %}
            </tbody>
        </table>
  </div>
</div>

  </body>
  </html>